// ignore_for_file: public_member_api_docs, sort_constructors_first

/// Represents a single answer option in Reverse Operation mode.
///
/// Each option shows an arithmetic expression (e.g., "5 + 5") and its
/// computed result so the engine can determine correctness.
class ReverseAnswerOption {
  final int firstNumber;
  final int secondNumber;
  final String operation;
  final int result;

  const ReverseAnswerOption({
    required this.firstNumber,
    required this.secondNumber,
    required this.operation,
    required this.result,
  });

  /// Human-readable expression string shown on the answer button.
  String get expressionLabel => '$firstNumber $operation $secondNumber';
}

/// Container for the data generated by [ReverseGameEngine.generateRound].
class ReverseRound {
  final int targetResult;
  final List<ReverseAnswerOption> options;
  final int correctIndex;

  const ReverseRound({
    required this.targetResult,
    required this.options,
    required this.correctIndex,
  });
}
